export const USER_ROLES = {
  ADMIN: 'ADMIN',
  KASIR: 'KASIR'
}

export const ACCOUNT_TYPES = {
  ASSET: 'ASSET',
  LIABILITY: 'LIABILITY',
  EQUITY: 'EQUITY',
  REVENUE: 'REVENUE',
  EXPENSE: 'EXPENSE'
}

export const TRANSACTION_TYPES = {
  CASH_REVENUE: 'CASH_REVENUE',
  CREDIT_REVENUE: 'CREDIT_REVENUE',
  RECEIVABLE_PAYMENT: 'RECEIVABLE_PAYMENT',
  OTHER_INCOME: 'OTHER_INCOME'
}

export const CREDIT_STATUS = {
  UNPAID: 'UNPAID',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID'
}
